---
title: "Results: Model Fit - Simple Mediation Model - Data Generated from a Nonnormal Distribution (Vale and Maurelli (1983) - Skewness = 3, Kurtosis = 21) - Complete Data - Structural Equation Modeling"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results: Model Fit - Simple Mediation Model - Data Generated from a Nonnormal Distribution (Vale and Maurelli (1983) - Skewness = 3, Kurtosis = 21) - Complete Data - Structural Equation Modeling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r}
library(jeksterslabRmedsimple)
data(results_vm_sev_fit.sem.mlr, package = "jeksterslabRmedsimple")
```

### Plots

#### Unstandardized

**Bias**

```{r fig.height = 8.5, fig.width = 11}
plot_bias(results_vm_sev_fit.sem.mlr)
```

**Root Mean Square Error**

```{r fig.height = 8.5, fig.width = 11}
plot_rmse(results_vm_sev_fit.sem.mlr)
```

**Kurtosis**

```{r fig.height = 8.5, fig.width = 11}
plot_kurt(results_vm_sev_fit.sem.mlr)
```
