---
title: "Results: Simple Mediation Model - Exponential X lambda = 1 - Complete Data - Fit Ordinary Least Squares"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results: Simple Mediation Model - Exponential X lambda = 1 - Complete Data - Fit Ordinary Least Squares}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r}
library(jeksterslabRmedsimple)
data(results_exp_fit.ols, package = "jeksterslabRmedsimple")
```

### Plots

#### Unstandardized

**Bias**

```{r fig.height = 8.5, fig.width = 11}
plot_bias(results_exp_fit.ols)
```

**Root Mean Square Error**

```{r fig.height = 8.5, fig.width = 11}
plot_rmse(results_exp_fit.ols)
```

**Kurtosis**

```{r fig.height = 8.5, fig.width = 11}
plot_kurt(results_exp_fit.ols)
```

#### Standardized

**Bias**

```{r fig.height = 8.5, fig.width = 11}
plot_bias(results_exp_fit.ols, std = TRUE)
```

**Root Mean Square Error**

```{r fig.height = 8.5, fig.width = 11}
plot_rmse(results_exp_fit.ols, std = TRUE)
```

**Kurtosis**

```{r fig.height = 8.5, fig.width = 11}
plot_kurt(results_exp_fit.ols, std = TRUE)
```
