---
title: "Results: Simple Mediation Model - Multivariate Normal Distribution - Data Missing at Random - Monte Carlo Method Confidence Intervals Structural Equation Modeling with Full Information Maximum Likelihood Parameter Estimates and Standard Errors"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results: Simple Mediation Model - Multivariate Normal Distribution - Data Missing at Random - Monte Carlo Method Confidence Intervals Structural Equation Modeling with Full Information Maximum Likelihood Parameter Estimates and Standard Errors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r}
library(jeksterslabRmedsimple)
data(results_mvn_mar_mc.mvn_ci, package = "jeksterslabRmedsimple")
```

### Plots

#### alpha 0.05

```{r fig.height = 8, fig.width = 11}
plot_type1(results_mvn_mar_mc.mvn_ci)
plot_power(results_mvn_mar_mc.mvn_ci)
plot_miss(results_mvn_mar_mc.mvn_ci)
```
