---
title: "Results: Confidence Intervals - Multivariate Normal - Data Missing Completely at Random"
author: "Ivan Jacob Agaloos Pesigan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results: Confidence Intervals - Multivariate Normal - Data Missing Completely at Random}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

```{r}
library(jeksterslabRmedsimple)
data(results_mvn_mcar_mc.mvn_ci, package = "jeksterslabRmedsimple")
data(results_mvn_mcar_nb.fiml_ci, package = "jeksterslabRmedsimple")
results_mcar_ci <- rbind(
  results_mvn_mcar_mc.mvn_ci,
  results_mvn_mcar_nb.fiml_ci
)
results_mcar_10_ci <- results_mcar_ci[which(results_mcar_ci$missing == "MCAR.10"), ]
results_mcar_20_ci <- results_mcar_ci[which(results_mcar_ci$missing == "MCAR.20"), ]
results_mcar_30_ci <- results_mcar_ci[which(results_mcar_ci$missing == "MCAR.30"), ]
```

### Plots

#### alpha 0.05

##### mcar_10

```{r fig.height = 8, fig.width = 11}
plot_type1(results_mcar_10_ci)
plot_power(results_mcar_10_ci)
plot_miss(results_mcar_10_ci)
```

##### mcar_20

```{r fig.height = 8, fig.width = 11}
plot_type1(results_mcar_20_ci)
plot_power(results_mcar_20_ci)
plot_miss(results_mcar_20_ci)
```

##### mcar_30

```{r fig.height = 8, fig.width = 11}
plot_type1(results_mcar_30_ci)
plot_power(results_mcar_30_ci)
plot_miss(results_mcar_30_ci)
```
